<h2 id="budgetteer-je-tijd">Budgetteer je tijd</h2>
<p>Aandacht is schaars. Afleiding is er in onvervloed. En steeds meer bedrijven concurreren om die schaarse aanbod. Met steeds interessantere, prikkelende en verslavende diensten.</p>
<p>Aandacht is één van de meest schaarse bezitten. Dagelijks is er een eindige hoeveelheid tot je beschikking. Meer dan ooit is het latig om te bepalen waar je aandacht aan geeft. De keuze wordt steeds groter. Aan nieuws dat altijd schreeuwend urgent oogt, ongeacht van wat er precies in de wereld gebeurt. Aan entertainment; Netflix, YouTube gepaard met steeds verfijndere algoritmes zodat er altijd wat te zien is bij jou past. Aan de overvloed van notificaties die continu je digitale leven binnensluipen, emails, apps, en zo verder.</p>
<p>Er zijn verschillende strategiëen te bedenken die hierop zijn toe te passen. Eén daarvan is te pogen alle prikkels zoveel mogelijk te minimalizeren. Geen nieuws, je smartphone uitbannen, Netflix afzweren. Randvoorwaardelijk is hierbij onuitputtelijke wilskracht. Om continu de verleiding van afleiding te weerstaan. Je voelt hem al aan; dat is vaak geen haalbare, structurele strategie.</p>
<p>In mijn ogen cruciaal is het introduceren van <em>intentie</em>. Waar ik zelf recent baat bij heb is het concept een <strong>tijdbudget</strong>. Het idee is dit: aan het begin van iedere werkdag geef je <strong>ieder komend half uur een taak</strong>. Voor ieder half uur specificeer je vooraf hoe je die gaat benutten. Input daarvoor haal je uit je vertrouwde organizatietools: agenda en takenlijst. Waarschijnlijk zullen een aantal blokken reeds gevuld zijn door reeds geplande afspraken.</p>
<p>Op deze manier kom je in de <em>driver’s seat</em> van je dag. Vooraf specifeer je hoe een optimale besteding van deze dag er uit zou kunnen zien. Geheid zullen er gedurende de dag allerlei curveballs gegooid worden op je plan. Geen probleem, gebruik het eerstvolgende beschikbaar moment om je plan bij te schaven. Met corrigeren is niets mis.</p>
<p>Het doel is niet het perfect uitvoeren van het voorgenomen plan. Het doel is om intentie te introduceren in je dag, en continu terug kunnen vallen op het feit dat de huidige activiteit precies datgene is wat je nu <em>zou moeten doen</em>. En ook dat er op gezette momenten in de dag om email en andere inboxes te managen, zodat niets tussen wel en schip valt.</p>
<p>Dat geeft rust.</p>
<p>Wees coulant voor jezelf. Een dag van voor tot achter dichtplannen is geen haalbaar recept. Plan pauzes, bijpraatmomenten, lunches evengoed in.</p>
<p>Door actief aan de slag te gaan met het budgetteren van tijd is het eenvoudig om te experimenteren met verschillende tactieken. Denk daarbij aan het</p>
<ul>
<li>Batchen van gelijkwaardige taken zoals telefoontjes en administratieve handelingen</li>
<li><em>Timen</em> van type activiteiten: uitdagend werk vroeg, als je nog fris bent; en routineklusjes aan het einde van de dag</li>
</ul>
